aws_region     = "ap-south-1"
medusa_image   = "venkatamahendrakalla/medusa-ecs:latest"
db_user        = "medusauser"
db_password    = "T3rrF0rmSecure#2025"
jwt_secret     = "T3rrF0rmSecure#2025"
